services:
  - type: web
    name: nova-lotto
    env: node
    plan: free
    region: ohio
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
      - key: NODE_ENV
        value: production
